name: news_portal
description: "뉴스 포탈 앱"
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  ####### Assets
  cupertino_icons: ^1.0.8
  lucide_icons_flutter: ^3.0.2

  ####### Core
  easy_extension:
    git:
      url: https://github.com/scadasystems/Easy-Extension.git
  easy_localization: ^3.0.7+1
  go_router: ^15.1.1
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/translations/ko-KR.json
    - assets/translations/en-US.json

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

